# Generated by Django 4.0 on 2021-12-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalquestionunit',
            name='point',
            field=models.IntegerField(default=1),
        ),
    ]
